//------------------------------------------------------------------------------
// <auto-generated>
//     Il codice è stato generato da uno strumento.
//     Versione runtime:4.0.30319.18444
//
//     Le modifiche apportate a questo file possono provocare un comportamento non corretto e andranno perse se
//     il codice viene rigenerato.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.0.30319.33440.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://schemas.microsoft.com/ado/2006/04/edm/ssdl")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://schemas.microsoft.com/ado/2006/04/edm/ssdl", IsNullable=false)]
public partial class Schema {
    
    private SchemaEntityContainer[] entityContainerField;
    
    private string namespaceField;
    
    private string providerField;
    
    private string providerManifestTokenField;
    
    private string aliasField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("EntityContainer")]
    public SchemaEntityContainer[] EntityContainer {
        get {
            return this.entityContainerField;
        }
        set {
            this.entityContainerField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Namespace {
        get {
            return this.namespaceField;
        }
        set {
            this.namespaceField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Provider {
        get {
            return this.providerField;
        }
        set {
            this.providerField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string ProviderManifestToken {
        get {
            return this.providerManifestTokenField;
        }
        set {
            this.providerManifestTokenField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Alias {
        get {
            return this.aliasField;
        }
        set {
            this.aliasField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://schemas.microsoft.com/ado/2006/04/edm/ssdl")]
public partial class SchemaEntityContainer {
    
    private SchemaEntityContainerEntitySet[] entitySetField;
    
    private string nameField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("EntitySet")]
    public SchemaEntityContainerEntitySet[] EntitySet {
        get {
            return this.entitySetField;
        }
        set {
            this.entitySetField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://schemas.microsoft.com/ado/2006/04/edm/ssdl")]
public partial class SchemaEntityContainerEntitySet {
    
    private string definingQueryField;
    
    private string nameField;
    
    private string entityTypeField;
    
    /// <remarks/>
    public string DefiningQuery {
        get {
            return this.definingQueryField;
        }
        set {
            this.definingQueryField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string EntityType {
        get {
            return this.entityTypeField;
        }
        set {
            this.entityTypeField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://schemas.microsoft.com/ado/2006/04/edm/ssdl")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://schemas.microsoft.com/ado/2006/04/edm/ssdl", IsNullable=false)]
public partial class NewDataSet {
    
    private Schema[] itemsField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Schema")]
    public Schema[] Items {
        get {
            return this.itemsField;
        }
        set {
            this.itemsField = value;
        }
    }
}
